spring:
  datasource:
    #   数据源基本配置
    username: root
    password: 333
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&allowMultiQueries=true
  jpa:
    hibernate:
    # 更新或者创建数据表结构
      ddl‐auto: update # 控制台显示SQL
    show‐sql: true